addpath("classes","functions","models");
clear_env();

%% define variables

datafile = "BTCUSDT.txt";

window_size = 90;
rate = 30;
no_samples = 1e4;
no_sets = 10;
prediction_length = 0;
time_before = 7*24*30;
time_after = 1*24*60;
confidence_interval = 0.4;
heuristic_limit = 0;
valid_split = 0.2;

batch_size = 512;
%adam options? 
learn_rate = 1e-3;
max_epochs = 30;

%% define model
%{
    9/9/2021
    code generated by deepnetworkdesigner
%}
lgraph = layerGraph();

tempLayers = [
    sequenceInputLayer(1,"Name","sequence_2")
    fullyConnectedLayer(256,"Name","fc_2")
    dropoutLayer(0.2,"Name","dropout_2")];
lgraph = addLayers(lgraph,tempLayers);

tempLayers = [
    fullyConnectedLayer(256,"Name","fc_3")
    dropoutLayer(0.2,"Name","dropout_3")
    reluLayer("Name","relu_1")];
lgraph = addLayers(lgraph,tempLayers);

tempLayers = [
    sequenceInputLayer(1,"Name","sequence_1")
    fullyConnectedLayer(256,"Name","fc_1")
    dropoutLayer(0.2,"Name","dropout_1")];
lgraph = addLayers(lgraph,tempLayers);

tempLayers = [
    fullyConnectedLayer(256,"Name","fc_5")
    dropoutLayer(0.2,"Name","dropout_5")
    reluLayer("Name","relu_2")];
lgraph = addLayers(lgraph,tempLayers);

tempLayers = [
    additionLayer(2,"Name","addition_3")
    groupNormalizationLayer("channel-wise","Name","groupnorm_3")];
lgraph = addLayers(lgraph,tempLayers);

tempLayers = [
    additionLayer(2,"Name","addition_1")
    groupNormalizationLayer("channel-wise","Name","groupnorm_1")];
lgraph = addLayers(lgraph,tempLayers);

tempLayers = [
    fullyConnectedLayer(256,"Name","fc_4")
    dropoutLayer(0.2,"Name","dropout_4")];
lgraph = addLayers(lgraph,tempLayers);

tempLayers = [
    additionLayer(2,"Name","addition_2")
    groupNormalizationLayer("channel-wise","Name","groupnorm_2")];
lgraph = addLayers(lgraph,tempLayers);

tempLayers = [
    concatenationLayer(1,2,"Name","concat")
    fullyConnectedLayer(256,"Name","fc_6")
    dropoutLayer(0.2,"Name","dropout_6")
    reluLayer("Name","relu_3")];
lgraph = addLayers(lgraph,tempLayers);

tempLayers = [
    additionLayer(2,"Name","addition_4")
    groupNormalizationLayer("channel-wise","Name","groupnorm_4")
    fullyConnectedLayer(256,"Name","fc_7")
    dropoutLayer(0.2,"Name","dropout_7")
    fullyConnectedLayer(1,"Name","fc_8")];
lgraph = addLayers(lgraph,tempLayers);

% clean up helper variable
clear tempLayers;

lgraph = connectLayers(lgraph,"dropout_2","fc_3");
lgraph = connectLayers(lgraph,"dropout_2","addition_1/in1");
lgraph = connectLayers(lgraph,"relu_1","addition_1/in2");
lgraph = connectLayers(lgraph,"dropout_1","fc_5");
lgraph = connectLayers(lgraph,"dropout_1","addition_3/in1");
lgraph = connectLayers(lgraph,"relu_2","addition_3/in2");
lgraph = connectLayers(lgraph,"groupnorm_3","concat/in1");
lgraph = connectLayers(lgraph,"groupnorm_3","addition_4/in1");
lgraph = connectLayers(lgraph,"groupnorm_1","fc_4");
lgraph = connectLayers(lgraph,"groupnorm_1","addition_2/in2");
lgraph = connectLayers(lgraph,"dropout_4","addition_2/in1");
lgraph = connectLayers(lgraph,"groupnorm_2","concat/in2");
lgraph = connectLayers(lgraph,"relu_3","addition_4/in2");

%%  training loop
model = cell(no_sets,1);

for s = 1:no_sets
    net = dlnetwork(lgraph);
    [train_samples,eval_samples] = get_samples(datafile,1,rate,time_before,time_after);
    [xData,yData] = subsample(train_samples{1},no_samples,window_size+1,prediction_length);
    [xVal,yVal] = subsample(eval_samples{1},valid_split*no_samples,window_size+1,prediction_length);
    
    gc = 1;
    [avg_g,avg_sqg] = deal([],[]);    
    tic;
    
    for epoch = 1:max_epochs
        
        locs = randperm(no_samples);
        
        for i = 1:batch_size:no_samples
            gc = gc+1;
            batch = [i:i+batch_size-1];
            batch(batch>no_samples) = [];
            
            xBatch = prepare_batch(xData(locs(batch)),'CTB');
            yBatch = prepare_batch(yData(locs(batch)),'CTB');
            
            [gradients,loss,net] = dlfeval(@model_gradients,net,xBatch,yBatch);
            [net,avg_g,avg_sqg] = adamupdate(net,gradients,avg_g,avg_sqg,gc,learn_rate);      
        end
        
        fprintf("epoch:\t%d, time_elapsed:\t%.2fs\tloss:\t%.2f\n",epoch,toc,loss);        
    end
    fprintf("\nmodel evaluation\n\n");
    evaluate_model(...
        eval_samples{1},net,window_size,prediction_length,false,true,0,confidence_interval,heuristic_limit);
    model{s} = net;    
    fprintf("\n");
end

%% helper functions 

function batch = prepare_batch(data,labels)
    batch = cell2mat(data);
    batch = reshape(batch,[1, size(batch,2), size(batch,1)]);
    batch = gpudl(batch,labels);
end

function data = gpudl(data,labels)
    data = gpuArray(dlarray(data,labels));  
end

function [gradients,loss,network] = model_gradients(network,xBatch,yBatch)
    
    y = forward(network,xBatch(:,:,2:end),yBatch(:,:,1:end-1));
    loss = sqrt(sum(power(y-yBatch(:,:,2:end),2),'all')/numel(y));

    gradients = dlgradient(loss,network.Learnables);
end











